### ISSUE TITLE
Image always black

### ISSUE THREAD

**Issue by Starraider** [LeoColomb/yourls-image-placeholder#1]
**Describe the bug**
The generated image is always black.

**To Reproduce**
See here:
https://skom.eu/320x70?c=cccccc

**Expected behavior**
The generated image should have the choosen color

**Actual behavior**
Its always black

**Screenshots**

**Versions**
* yourls-image-placeholder: Current master branch
* yourls: 1.8.1

**Comment by LeoColomb** [comment]
Thanks for opening this ticket @Starraider.
The reported behavior is quite strange...
Can you upload here the logs if any generated by php on a request?
Also, which version of PHP are you using?

**Comment by alfianridwan** [comment]
Hey @Starraider and @LeoColomb , I face the same problems as well. I'm currently using PHP version 7.3.29. How do I view the logs?
