### ISSUE TITLE
No image generated

### ISSUE THREAD

**Issue by wassereimer86** [LeoColomb/yourls-image-placeholder#3]
**Describe the bug**
No image generated

**Expected behavior**
An image generated

**Actual behavior**
No image generated

**Versions**
Newest Docker Container

**Additional context**
https://xxx/800x400

results in

https://bilderupload.org/bild/522726385-chrome-2022-10-02-17-58-0

**Comment by LeoColomb** [comment]
Thanks for opening this issue @wassereimer86.
That being said, so little information is provided that no support is possible.

Could you elaborate the error?
Any log to share?

**Comment by wassereimer86** [comment]
I don't know what more I can say. I couldn't find any error message or something else. And yourls is new to me. The plugin loaded normally. Did you try to use it in the docker container? In the "normal" installation, the plugin is working. I don't run it in the docker container anymore. It was just for testing purposes, and I wanted to let you know what I knew so far.

**Comment by LeoColomb** [comment]
I see.
Indeed, the plugin require additional PHP extensions that are most probably not provided within the base container image.
I've added the requirement on the README for clarification.
Glad to read it actually work on your side.
